import { spawn } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const env=process.env,required=["SIGNALFLOW_URL","ICECAST_HOST","ICECAST_PORT","ICECAST_MOUNT","ICECAST_SOURCE_USER","ICECAST_SOURCE_PASSWORD"];
for(const key of required)if(!env[key])throw new Error(`Missing required setting: ${key}`);

const site=env.SIGNALFLOW_URL.replace(/\/$/,""),sampleRate=Number(env.AUDIO_SAMPLE_RATE||44100),channels=Number(env.AUDIO_CHANNELS||2),format=(env.AUDIO_FORMAT||"mp3").toLowerCase();
if(!Number.isInteger(sampleRate)||![1,2].includes(channels)||!["mp3","aac"].includes(format))throw new Error("Invalid audio format settings");

const siteHeaders=env.SIGNALFLOW_SITE_TOKEN?{"OAI-Sites-Authorization":`Bearer ${env.SIGNALFLOW_SITE_TOKEN}`}:{},ffmpegHeader=env.SIGNALFLOW_SITE_TOKEN?`OAI-Sites-Authorization: Bearer ${env.SIGNALFLOW_SITE_TOKEN}\r\n`:"";
let encoder=null,decoder=null,fetcher=null,activeSignature="",pendingSignature="",lastPcm=0,stopping=false;
const mediaCache=new Map();
const startedItems=new Set();
const log=(...args)=>console.log(new Date().toISOString(),...args);
const icecastUrl=()=>{const auth=`${encodeURIComponent(env.ICECAST_SOURCE_USER)}:${encodeURIComponent(env.ICECAST_SOURCE_PASSWORD)}`,mount=env.ICECAST_MOUNT.startsWith("/")?env.ICECAST_MOUNT:`/${env.ICECAST_MOUNT}`;return`icecast://${auth}@${env.ICECAST_HOST}:${env.ICECAST_PORT}${mount}`};

function encoderArgs(){const codec=format==="aac"?["-c:a","aac","-f","adts","-content_type","audio/aac"]:["-c:a","libmp3lame","-f","mp3","-content_type","audio/mpeg"];return["-hide_banner","-loglevel","warning","-re","-f","s16le","-ar",String(sampleRate),"-ac",String(channels),"-i","pipe:0",...codec,"-b:a",env.AUDIO_BITRATE||"128k","-ice_name",env.STATION_NAME||"SignalFlow Radio","-ice_description",env.STATION_DESCRIPTION||"SignalFlow continuous playout","-ice_url",env.STATION_URL||"","-ice_public",env.ICECAST_PUBLIC==="true"?"1":"0",...(env.ICECAST_TLS==="true"?["-tls","1"]:[]),icecastUrl()]}
function startEncoder(){if(encoder||stopping)return;log("Connecting continuous output to Icecast");encoder=spawn("ffmpeg",encoderArgs(),{stdio:["pipe","ignore","pipe"]});encoder.stderr.on("data",data=>process.stderr.write(data));encoder.stdin.on("error",()=>{});encoder.on("exit",code=>{log(`Icecast encoder stopped (${code}); reconnecting`);encoder=null;if(!stopping)setTimeout(startEncoder,2000)})}

function stopProcess(process){if(process&&!process.killed)process.kill("SIGTERM")}
function stopDecoder(){stopProcess(fetcher);stopProcess(decoder);fetcher=null;decoder=null;activeSignature="";pendingSignature=""}
function signature(status){return status.current?.id||""}
function playbackUrl(item){return item.kind==="stream"?`/api/stream/${item.assetId}`:`/api/media/${item.assetId}`}
function preRoll(status){const next=status.next,start=next?new Date(next.startAt).getTime():0,lead=start-Date.now();if(!status.current||!status.playbackUrl||!next||lead<=0||lead>3000)return status;const naturalEnd=new Date(status.current.endAt).getTime(),hasAudioTail=status.current.kind==="upload"&&naturalEnd>start,fadeEnd=hasAudioTail?status.current.endAt:new Date(start+3000).toISOString(),outgoing={...status.current,endAt:fadeEnd,fadeStartAt:next.startAt,playbackUrl:status.playbackUrl};return{...status,current:next,playbackUrl:playbackUrl(next),overlays:[outgoing]}}
async function cacheUpload(item,playbackUrl){const key=item.assetId;if(mediaCache.has(key))return mediaCache.get(key);const task=(async()=>{const response=await fetch(new URL(playbackUrl,site),{headers:siteHeaders,signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Audio download returned HTTP ${response.status}`);const bytes=Buffer.from(await response.arrayBuffer());if(!bytes.length)throw new Error("Downloaded audio file was empty");const path=join(tmpdir(),`signalflow-${key}.audio`);await writeFile(path,bytes);log(`Cached ${item.title} (${Math.round(bytes.length/1024)} KB)`);return path})().catch(error=>{mediaCache.delete(key);throw error});mediaCache.set(key,task);return task}
async function startDecoder(status,wanted){
  if(!status.current||!status.playbackUrl)return;pendingSignature=wanted;
  let inputs=[...(status.overlays||[]).map(item=>({item,playbackUrl:item.playbackUrl,outgoing:true})),{item:status.current,playbackUrl:status.playbackUrl,outgoing:false}];
  try{inputs=await Promise.all(inputs.map(async input=>input.item.kind==="upload"?{...input,playbackUrl:await cacheUpload(input.item,input.playbackUrl)}:input));if(stopping||pendingSignature!==wanted)return;
  const now=Date.now(),args=["-hide_banner","-loglevel","warning"],overrideHost=env.STREAM_HOST_OVERRIDE_HOST?.trim(),overrideIp=env.STREAM_HOST_OVERRIDE_IP?.trim();let override=null;
  for(const input of inputs){let url=input.item.kind==="upload"?input.playbackUrl:input.playbackUrl.startsWith("/")?new URL(input.playbackUrl,site).toString():input.playbackUrl,remote=input.item.kind==="stream"&&input.item.sourceUrl?new URL(input.item.sourceUrl):null,useOverride=!!remote&&!!overrideHost&&!!overrideIp&&remote.hostname===overrideHost&&!override;if(useOverride){url="pipe:0";override=remote}args.push("-thread_queue_size","2048");if(input.item.kind==="upload")args.push("-analyzeduration","20000000","-probesize","20000000");if(url.startsWith(site)&&ffmpegHeader)args.push("-headers",ffmpegHeader);const rawElapsed=Math.max(0,(now-new Date(input.item.startAt).getTime())/1000),protectOpening=input.item.kind==="upload"&&!input.outgoing&&!startedItems.has(input.item.id)&&rawElapsed<=5,elapsedBase=protectOpening?0:rawElapsed,elapsed=input.item.loop&&input.item.durationSeconds?elapsedBase%input.item.durationSeconds:elapsedBase;input.elapsed=elapsed;if(!input.outgoing)startedItems.add(input.item.id);if(input.item.loop)args.push("-stream_loop","-1");args.push("-i",url)}
  const currentRemaining=Math.max(.1,(new Date(status.current.endAt).getTime()-now)/1000),pipelineRemaining=Math.max(currentRemaining,...inputs.filter(input=>input.outgoing).map(input=>Math.max(.1,(new Date(input.item.endAt).getTime()-now)/1000)));
  const filters=[],labels=[],layout=channels===1?"mono":"stereo";
  inputs.forEach((input,index)=>{const chain=[],startsIn=Math.max(0,(new Date(input.item.startAt).getTime()-now)/1000);if(input.item.kind==="upload"&&input.elapsed>.01)chain.push(`atrim=start=${input.elapsed.toFixed(3)}`,"asetpts=PTS-STARTPTS");if(!input.outgoing&&startsIn>.01&&input.item.kind==="stream")chain.push(`atrim=start=${startsIn.toFixed(3)}`,"asetpts=PTS-STARTPTS");chain.push(`aresample=${sampleRate}:async=1:first_pts=0`,`aformat=sample_fmts=s16:sample_rates=${sampleRate}:channel_layouts=${layout}`);if(!input.outgoing&&startsIn>.01&&input.item.kind==="upload")chain.push(`adelay=${Math.round(startsIn*1000)}:all=1`);if(input.outgoing){const fadeStart=Math.max(0,(new Date(input.item.fadeStartAt||now).getTime()-now)/1000),fadeEnd=Math.max(fadeStart+.1,(new Date(input.item.endAt).getTime()-now)/1000);chain.push(`afade=t=out:st=${fadeStart.toFixed(3)}:d=${(fadeEnd-fadeStart).toFixed(3)}`)}else if(input.item.kind==="stream"&&input.item.timingType==="flexible")chain.push(`afade=t=out:st=${Math.max(0,currentRemaining-3).toFixed(3)}:d=${Math.min(3,currentRemaining).toFixed(3)}`);const label=`in${index}`;filters.push(`[${index}:a]${chain.join(",")}[${label}]`);labels.push(`[${label}]`)});
  if(inputs.length>1){filters.push(`${labels.join("")}amix=inputs=${inputs.length}:duration=longest:dropout_transition=0:normalize=0,alimiter=limit=0.95[mix]`);args.push("-filter_complex",filters.join(";"),"-map","[mix]")}
  else args.push("-filter_complex",filters.join(";"),"-map",labels[0]);
  args.push("-t",pipelineRemaining.toFixed(3),"-vn","-f","s16le","-acodec","pcm_s16le","-ar",String(sampleRate),"-ac",String(channels),"pipe:1");
  const description=inputs.length>1?`Mixing ${(status.overlays||[]).map(item=>item.title).join(", ")} under ${status.current.title}`:`Starting ${status.current.title} (${status.current.id})`,candidate=spawn("ffmpeg",args,{stdio:[override?"pipe":"ignore","pipe","pipe"]});let candidateFetcher=null,promoted=false;
  if(override){const port=override.port||(override.protocol==="https:"?"443":"80");log(`Using DNS override ${overrideHost} -> ${overrideIp}`);candidateFetcher=spawn("curl",["--fail","--silent","--show-error","--location","--no-buffer","--resolve",`${overrideHost}:${port}:${overrideIp}`,override.toString()],{stdio:["ignore","pipe","pipe"]});candidateFetcher.stdout.pipe(candidate.stdin);candidateFetcher.stderr.on("data",data=>process.stderr.write(data));candidateFetcher.on("exit",()=>candidate.stdin.end());candidate.stdin.on("error",()=>{})}
  candidate.stdout.on("data",chunk=>{if(stopping||pendingSignature!==wanted&&!promoted){stopProcess(candidateFetcher);stopProcess(candidate);return}if(!promoted){const oldDecoder=decoder,oldFetcher=fetcher;decoder=candidate;fetcher=candidateFetcher;activeSignature=wanted;pendingSignature="";promoted=true;log(description);if(oldDecoder&&oldDecoder!==candidate)log("Warm handover completed");stopProcess(oldFetcher);stopProcess(oldDecoder)}if(decoder!==candidate)return;lastPcm=Date.now();if(encoder?.stdin.writable&&!encoder.stdin.write(chunk)){candidate.stdout.pause();encoder.stdin.once("drain",()=>{if(decoder===candidate)candidate.stdout.resume()})}});candidate.stderr.on("data",data=>process.stderr.write(data));candidate.on("exit",code=>{if(!promoted){stopProcess(candidateFetcher);if(pendingSignature===wanted){pendingSignature="";log(`Replacement source failed before handover (${code})`)}}else if(decoder===candidate){log(`Source pipeline ended (${code})`);decoder=null;fetcher=null;if(activeSignature===wanted)activeSignature=""}})}catch(error){if(pendingSignature===wanted)log(`Couldn’t prepare source: ${error.message}`)}
}

async function readStatus(){const response=await fetch(`${site}/api/now`,{headers:siteHeaders,signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`SignalFlow returned HTTP ${response.status}`);return response.json()}
async function scheduleLoop(){while(!stopping){try{const live=await readStatus();if(live.next?.kind==="upload")void cacheUpload(live.next,`/api/media/${live.next.assetId}`).catch(error=>log(`Couldn’t pre-cache ${live.next.title}: ${error.message}`));const status=preRoll(live),wanted=signature(status);if(wanted!==activeSignature&&wanted!==pendingSignature)void startDecoder(status,wanted)}catch(error){log(error.message)}await new Promise(resolve=>setTimeout(resolve,250))}}

const silenceBytes=Math.floor(sampleRate*channels*2/10),silence=Buffer.alloc(silenceBytes);setInterval(()=>{if(!stopping&&Date.now()-lastPcm>2000&&encoder?.stdin.writable&&!encoder.stdin.writableNeedDrain)encoder.stdin.write(silence)},100);
function shutdown(){stopping=true;stopDecoder();if(encoder){encoder.stdin.end();setTimeout(()=>encoder?.kill("SIGTERM"),1000)}setTimeout(()=>process.exit(0),2000)}
process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);startEncoder();scheduleLoop();
